version: '3.7'

services:
  minecraft_vanilla:
    image: itzg/minecraft-server:adopt14
    restart: always
    depends_on:
      - postgres
      - graphql-engine
    environment:
      EULA: "true"
      ONLINE_MODE: "TRUE"
      TYPE: PAPER
      VERSION: '$MORDRUM_MINECRAFT_VERSION'
      MAX_MEMORY: '$MORDRUM_MINECRAFT_MAX_MEMORY'
      USE_AIKAR_FLAGS: "TRUE"
      USE_LARGE_PAGES: "TRUE"
      MAX_BUILD_HEIGHT: 256
      VIEW_DISTANCE: 15
      LEVEL_TYPE: LARGEBIOMES
      MAX_PLAYERS: '$MORDRUM_MINECRAFT_MAX_PLAYERS'
    ports:
      - '$MORDRUM_MINECRAFT_PORT:25565'
    volumes:
      - ./vanilla_data:/data
        # bungeecord:
        #    image: itzg/bungeecord
        #    environment:
        #      TYPE: VELOCITY
        #      VELOCITY_VERSION: "1.1.2"
        #    ports:
        #      - 25565:25577
        #    volumes:
        #      - ./config.yml:/server/config.yml
  postgres:
    image: postgres:13-alpine
    ports:
      - '$MORDRUM_POSTGRES_PORT:5432'
    restart: always
    environment:
      POSTGRES_PASSWORD: '$MORDRUM_POSTGRES_PASSWORD'
      POSTGRES_USER: '$MORDRUM_POSTGRES_USERNAME'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v2.0.0-alpha.2
    ports:
      - '$MORDRUM_HASURA_PORT:8080'
    depends_on:
      - postgres
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://$MORDRUM_POSTGRES_USERNAME:$MORDRUM_POSTGRES_PASSWORD@postgres:$MORDRUM_POSTGRES_PORT/$MORDRUM_POSTGRES_USERNAME
      HASURA_GRAPHQL_ADMIN_SECRET: '$MORDRUM_HASURA_ADMIN_SECRET'
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"

volumes:
  postgres_data:
